### ISSUE TITLE
Update Image overview on dockerhub (Typo)

### ISSUE THREAD

**Issue by momo3334** [mkuf/prind#102]
There are some discrepancies between the different image overviews on docker hub. I guess those were small typos but nevertheless they caused me a lot of head scratching when i wanted to run klipper and moonraker in standalone mode. 

The major one i noticed is this one.

## Run configuration from the _mkuf/moonraker_ in Docker Hub

![Screenshot 2023-12-06 162700](https://github.com/mkuf/prind/assets/37804459/37f97d72-0a05-444a-8e51-cb9f5c926be9)

## Run configuration from the _mkuf/klipper_ in Docker Hub

![Screenshot 2023-12-06 162229](https://github.com/mkuf/prind/assets/37804459/1cb646e8-6a69-401a-b783-2c4e2b5b0275)

**Comment by mkuf** [comment]
Hey there, 
Great catch, thanks for reaching out. 

Docs have been updated in https://github.com/mkuf/prind/commit/c0bac1e729d1b2ca17e1c10c4eb01541b35362b9 and I also updated the Description on Dockerhub. 

-Markus
