### ISSUE TITLE
Fluidd starts as mainsail and klipper can't connect

### ISSUE THREAD

**Issue by InfiniteCoder01** [mkuf/prind#104]
Sometimes it works, but sometimes, when I do `docker compose --profile fluidd up` instead of getting fluidd, I get Mainsail loading. And it can't connect to moonraker. When I actually do `docker compose --profile mainsail up`, sometimes it works, but sometimes it just can't connect to klipper. Note, that I've set traefik port to be "2024:80", because I have CasaOS running with some other services.

**Comment by mkuf** [comment]
Any update on this?
