### ISSUE TITLE
[Feature] Add support for monitoring the containers

### ISSUE THREAD

**Issue by zackbcom** [mkuf/prind#109]
# Add support for monitoring performance on device
I have added support for monitoring the docker stack and host. I am using [glances](https://glances.readthedocs.io/en/latest/index.html) [docker container](https://glances.readthedocs.io/en/latest/docker.html#docker-1).

Doesn't have support for monitoring the pi gpu yet.

Need to have the last slash to get the page to load. I havn't looked at what the fix is yet.
ex: `http://192.168.2.109/glances/`

```Dockerfile
  monitoring:
    image: nicolargo/glances:latest-full 
    restart: always
    pid: host
    ports:
      - 61208:61208
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "GLANCES_OPT=-w"
    labels:
      traefik.enable: true
      traefik.http.services.glances.loadbalancer.server.port: 61208
      traefik.http.routers.glances.rule: PathPrefix(`/glances`)
      traefik.http.routers.glances.entrypoints: web
      traefik.http.middlewares.glances.stripprefix.prefixes: /glances
      traefik.http.routers.glances.middlewares: glances
```

## Screenshots
- Using dockertag:`ubuntu-latest-full `
  - <img width="1432" alt="image" src="https://github.com/mkuf/prind/assets/1888323/ecfb3268-0f0d-4692-b627-fe8d69775296">
- Using dockertag:`latest-full `
  - <img width="1432" alt="image" src="https://github.com/mkuf/prind/assets/1888323/83b3ceba-6c7d-47a3-940f-183a48f935a9">

**Comment by mkuf** [comment]
Hi there, 
thanks for reaching out. 

While this may be useful for some, monitoring and metrics are very specific to the users needs, so they are out of scope for this project.  
That said, I really like the minimal approach glances takes to display metrics, so I created a custom file in https://github.com/mkuf/prind/commit/f88e65f91eb06fb68a9d5b9bb8d0860ceb4750f7, that may be used to add this service to the stack. This also adds an additional middleware in traefik which takes care of the trailing slash. 

-Markus
