### ISSUE TITLE
Guide Assistance

### ISSUE THREAD

**Issue by BigRocketCannon** [mkuf/prind#149]
I am not sure if this is the right place, but I am new to creating docker containers and would like to use this project. Is there a step by step guide for more beginners like me? Or maybe (if given some guidance on getting started) I could assist with writing one?

Thank you for your assistance.

**Comment by mkuf** [comment]
Hi there,

did you have a look at the main Readme of this repository?  
Following the [getting started](https://github.com/mkuf/prind?tab=readme-ov-file#getting-started) section should get you up an runnig quickly.  
Let me know if you see any room for Improvement.
