### ISSUE TITLE
apprise for moonraker notification

### ISSUE THREAD

**Issue by luckydevil13** [mkuf/prind#160]
Hi, could you  please be kind to add apprise docker image (separate or inside moonraker) for support notifications via moonraker?

**Comment by mkuf** [comment]
Apprise is already installed in the moonraker container image as it is part of the [upstream requirements](https://github.com/Arksine/moonraker/blob/master/scripts/moonraker-requirements.txt)

```
~$ docker run --rm -it --entrypoint bash mkuf/moonraker:latest

moonraker@5a1bfaf880dd:/opt$ ./venv/bin/pip freeze

WARNING: The directory '/home/moonraker/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
apprise==1.8.0
certifi==2024.6.2
charset-normalizer==3.3.2
[...]
```

Do you have any logs that indicate apprise is missing?

**Comment by luckydevil13** [comment]
thanks!
