### ISSUE TITLE
Abort print on error?

### ISSUE THREAD

**Issue by mhaas** [mkuf/prind#49]
Hi,

I found this issue earlier: https://github.com/Klipper3d/klipper/issues/3666

It seems that Klipper does not turn off the heater in certain error conditions.

To make this repo failsafe by default, what do you think about adding the [following](https://github.com/Klipper3d/klipper/issues/3666#issuecomment-1146197783):

```
[virtual_sdcard]
; other stuff here...
on_error_gcode:
  CANCEL_PRINT
```

**Comment by mkuf** [comment]
Hi there, 
Thanks for raising this issue.   

This would definitely make sense as failsafe for beginners.  
For more advanced users calling the `CANCEL_PRINT` macro may not be the right choice. 

It is the users responsibility to configure the services for their specific needs in a safe way.
I therefore intend to keep the configs as minimal as possible. 

-Markus
