### ISSUE TITLE
Flashing the micro-controller

### ISSUE THREAD

**Issue by speendo** [mkuf/prind#5]
This is a great project! I hope you continue your work on it!

I just noticed, that it seems that there is currently no option to flash the micro-controller of the 3D printer.

What I tried:

* I entered the "klipper" docker container with `$ docker exec -it klipper /bin/bash`
* I changed the directory to `/opt/klipper`
* I tried to run `$ make menuconfig` but got the response that the command make is not available: `bash: make: command not found`

I was able to quick-fix this problem by entering the container as root (`$ docker exec -it --user root klipper /bin/bash`) installing make with

    $ apt update; apt install build-essential gcc-arm-none-eabi

(The latter package is only necessary for ARM micro-controllers. As I use a BigTreeTech SKR1.4 Pro, I need it.)

After that I was able to run `make menuconfig` and `make`. However this increased the size of the docker container by about 2 GB and it might still be a little clumsy to obtain the files generated by the script afterwards as they are stored inside the docker container. I think there could be a more convenient solutions for this.

**Comment by mkuf** [comment]
Hi there, 

the `klipper` container that is started with compose only contains the runtime packages for klippy and is not suited for building mcu binaries. 
Building and flashing the mcu code requires you to use the `*-mcu` image as described here. 
https://github.com/mkuf/prind#building-mcu-code

-Markus
