### ISSUE TITLE
I want use CAN bus as device connect how to update yaml config?

### ISSUE THREAD

**Issue by mela93** [mkuf/prind#52]
this is Serial Port config at docker-compose.override.yaml
```
klipper:
  devices:
    - /dev/serial/by-id/xxx-example:/dev/serial/by-id/xxx-example
```

when i use can bus,
the printer.cfg will change to this, and how to update docker-compose.override.yaml?
```
[mcu]
#serial: /dev/serial/by-id/xxx-example
canbus_uuid: 9999c29dd86f
canbus_interface: can0
```

**Comment by mkuf** [comment]
Hi there, 

I have no experience using CAN bus. Neither with klipper nor with docker.
A quick google search pointed me to this stackoverflow thread: https://stackoverflow.com/questions/69078501/how-to-make-can-bus-operate-from-within-a-docker-container

Following this example, you can remove the device section from the klipper service and add the host network like so:

```yaml
services:
  klipper:
    network_mode: host
```

Let me know if this works for you. 

-Markus

**Comment by mela93** [comment]
Yes, it works.
Thank you so much.
