### ISSUE TITLE
Documentation: the command is called "docker-compose"

### ISSUE THREAD

**Issue by speendo** [mkuf/prind#6]
Just another small thing: in the documentation you mention to run `docker compose <something>` but it should probably be `docker-compose <something>`.

**Comment by mkuf** [comment]
Hi there, 

the examples refer to docker compose v2, which is a plugin to docker and not a standalone tool anymore. 
I updated the docs in https://github.com/mkuf/prind/commit/88658dfa542e2e5ba3c20ca9bff0ca879e3c320b to clear this up. 

-Markus
