### ISSUE TITLE
Recommended way to add plugins to the prind stack

### ISSUE THREAD

**Issue by aguinaldoabbj** [mkuf/prind#60]
Hi,

What would be the recommended way (without breaking things our rebuilding stuff) to install a plugin like [moonraker-obico)](uhttps://github.com/TheSpaghettiDetective/moonraker-obico) on prind ?

Thanks in advance.

**Comment by mkuf** [comment]
Hi there, 

that depends on the way the plugin is supposed to be installed.  

Plugins that need to live inside a specific container require you to create a dockerfile based on the prind image but with added functionality, see https://github.com/mkuf/prind/issues/46#issuecomment-1342964135 for reference.

Looking at the moonraker-obico plugin you mentioned, it does not seem to actually need to be run in the same container as moonraker. So, you could ask at https://github.com/TheSpaghettiDetective/moonraker-obico if they're willing to provide a container image of their application, which then could be added to the main docker-compose of prind.

If the project you'd like to implement is unwilling to provide container images, you may create a directory under `docker/` and add a build step to the compose file as described in https://github.com/mkuf/prind#building-docker-images-locally.

-Markus
