### ISSUE TITLE
setup-X11.sh link is broken on DockerHub

### ISSUE THREAD

**Issue by pauhull** [mkuf/prind#61]
On https://hub.docker.com/r/mkuf/klipperscreen, setup-X11.sh points to a 404

**Comment by mkuf** [comment]
Hi there, 
The readme is part of this repository and therefore uses a relative path to the script. 
This makes it portable and also works if this repository is forked or hosted anywhere else.

My current workflow is to manually copy/paste the readme to dockerhub if anything changes.  
Even if I update the link there this one time, I won't think about it the next time I update the readme. 

Anyone using the Image can be expected to follow the link at top of the readme on dockerhub to find the script within the github repo. 

-Markus
