### ISSUE TITLE
Unable to find DBus PolKit Interface

### ISSUE THREAD

**Issue by GAZ082** [mkuf/prind#65]
Im getting that error in Mainsail, for what I researched, some script must be run in moonraker.

https://github.com/Arksine/moonraker/issues/349

Dont know if this still applies today. Thanks!

![image](https://user-images.githubusercontent.com/100194/224503562-0437c5d5-08e2-4b79-a7ac-d9be5c7f84f7.png)

**Comment by kevinpastor** [comment]
I've been having the same issue for a long time too.

**Comment by mkuf** [comment]
This warning can usually be ignored, as moonraker is running in docker and does not need to restart services.  
Can you verify that host reboot/shutdown is working?

-Markus

**Comment by GAZ082** [comment]
Its working and this error disappeared a few days ago.
