### ISSUE TITLE
Moonraker / Timelapse

### ISSUE THREAD

**Issue by ChrQR** [mkuf/prind#68]
First off all thank you for providing this repo, which makes it super easy to use in Docker. I just have one small request for moonraker timelapse to get installed either by default or as a profile.

If it is already in the image, please point me in the right direction of enabling it.

**Comment by mkuf** [comment]
Hi there, 

see https://github.com/mkuf/prind/issues/46 for Info on how to get timelapse up and running. 

Closing this as duplicate.  
Feel free to reply at the linked issue if you need further help with this topic. 

-Markus
