### ISSUE TITLE
Workaround for docker not supporting symlinks?

### ISSUE THREAD

**Issue by GAZ082** [mkuf/prind#69]
I want to use stow to save my config files. When I do the symlinks i got errors. Now, when i check inside the klipper container i see that the locations are pointed to where the linked file is and its not taking the softlink. I found that Docker does not like symlinks. How can I edit the config files to let them know the new location? Everything seems cryptic. Thanks!

![image](https://user-images.githubusercontent.com/100194/229957217-4cb665f6-12c1-4ba6-9b3e-b93e7556921d.png)

**Comment by mkuf** [comment]
Hello, 

it's not like docker is incompatible with symlinks. Symlinks do not work the way you intend to use them.   
A symlink is just like a road sign pointing to the location of a file, not a "tunnel" through wich the file can be accessed.  
  
So, to get your symlinks to work, you'll have to also mount the directory containing your files into the container.  
From the screenshot you posted, the `.dotfiles` directory should be mounted at `/opt/.dotfiles` within the container. 

-Markus
