### ISSUE TITLE
So no Input Shaper?

### ISSUE THREAD

**Issue by boehser-enkel** [mkuf/prind#71]
> Running a host_mcu process on a RaspberryPi to access its GPIO pins is currently not possible when running in Docker. Feel free to contribute if you have a Solution for this.

So no Input Shaping on a RPI with Docker possible. Did i get this correctly? 
Because the text goes on if it would be possible

greetings

**Comment by mkuf** [comment]
Hey there, 

all requirements for input shaping are installed in the container images.   

Calibration does work, as long as the accelerometer is directly connected to your printers mcu or you use a USB connected accelerometer and add the device to your docker-compose.override.yaml. 

The passage you mentioned is about input shaper calibration using a accelerometer connected to a raspberry pi, which is currently not supported as I do not own hardware to verify this.  

-Markus
