### ISSUE TITLE
machine configuration in moonraker.cfg

### ISSUE THREAD

**Issue by speendo** [mkuf/prind#8]
the default `moonraker.cfg` gives me this warning in the dashboard screen
![grafik](https://user-images.githubusercontent.com/1668429/152622681-b2d8c414-ca04-4e97-9541-6f6ec59716de.png)

When I add

    [machine]
    provider: systemd_cli

to `moonraker.cfg` the warning goes away.

If I am not mistaken, this is a very new feature in Moonraker (only 7 days old)
https://github.com/Arksine/moonraker/commit/be338ad0396c4e5e69510f4be5eaa4a67f2120bb

**Comment by mkuf** [comment]
Hi there, 

thanks for bringing this to my attention. 

According to the moonraker docs `none` would be the correct value for this configuration option as there is no systemd command within the moonraker container. 
https://github.com/Arksine/moonraker/blob/9e9f9ee0fd49e82d6362c1b054d0068204d5a00a/docs/configuration.md#machine

I added the appropriate config in https://github.com/mkuf/prind/commit/a1ab053d4010c23516b00396504f41d5a5b9261e

-Markus
