### ISSUE TITLE
Allow modifiable UID and GID

### ISSUE THREAD

**Issue by Nite16** [mkuf/prind#85]
Requesting the ability to have the containers create and use a customizable UID and GID since my existing UID 1000 and GID 1000 is a user and group I don't want to have the level of access required to make the stack work.

**Comment by mkuf** [comment]
Hi, 
I've seen this feature in some existing containers where it is possible to do this via environment variables.  
That said, this approach would add a lot of complexity to the images I'd like to avoid.  
If this is requested by a significant amount of the userbase, I'd consider it for the next iterations.  
So, if anyone else is reading this, please add to this conversation and state your usecase.

In the meantime, I suggest building your own images based on the upstream moonraker and klipper images and modify the uid/gid to your requirements. I added an example override file in https://github.com/mkuf/prind/commit/cc3564f1c811ca731c003f55bbbd051f91c42730, which accomplishes just that.

https://github.com/mkuf/prind/blob/cc3564f1c811ca731c003f55bbbd051f91c42730/custom/docker-compose.custom.unique-uid-gid.override.yaml#L1-L63

-Markus
